algoritmo "10"
// Função :
// Autor : Esther Oliveira costa
// Data : 14/09/2020
// Seção de Declarações 
var

numero,contador,fatorial: inteiro

inicio
escreval(" digite um número inteiro:")
leia (numero)


contador <-1
fatorial <-1

enquanto contador <= numero faca
   fatorial <- fatorial* contador
   contador <- contador + 1
   
   fimenquanto
   
escreval (" o fatorial de numero e igual a : ", fatorial )

fimalgoritmo
