algoritmo "8"
// Função :
// Autor :  Esthe oliveira costa
// Data : 14/09/2020
// Seção de Declarações 
var
n,soma, cont :inteiro
media : real
inicio


repita

escreval (" digite um numero :")
leia (n)

se n%2=0 entao
se n<>0 entao
cont <- cont +1
media <- soma + cont
fimse

se n = 0 entao
escreval (" fim da lista de valores ")
fimse
fimse
ate n=0


escreval (" a media dos numeros  e ", media )


fimalgoritmo
